version: '3.8'

services:
  app:
    container_name: o_me_api
    build: 
      context: .
      dockerfile: ./dockerfile
    restart: always
    ports:
      - 3338:3338
    env_file:
      - .env
    volumes:
      - .:/usr/backend/src